########################
# NIFI
########################    
apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: cephfs
  labels:
    app: hadoop
spec:
  ports:
    - port: 8181
      targetPort : 8181
      name: nifi
  selector:
    app: hadoop
    tier: nifi
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: cephfs
  labels:
    app: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop
  serviceName: nifi
  replicas: 1
  template:
    metadata:
      labels:
        app: hadoop
        tier: nifi  
    spec:
      containers:
      - name: nifi
        image: apache/nifi:latest
        env:
        - name: NIFI_WEB_HTTP_PORT
          value: "8181"
        - name: NIFI_WEB_HTTP_HOST
          value: "nifi-0"
        ports:
        - containerPort: 8181
          name: nifi
          hostPort: 8181
        volumeMounts:
        - name: nifi-data-in
          mountPath: /data_in
        - name: nifi-data-out
          mountPath: /data_out
        - name: nifi-conf
          mountPath: /opt/nifi/nifi-1.5.0/conf
        - name: nifi-config-hadoop-core-site
          mountPath: /etc/hadoop/conf/core-site.xml
          subPath: core-site.xml
        - name: nifi-config-hadoop-hdfs-site
          mountPath: /etc/hadoop/conf/hdfs-site.xml
          subPath: hdfs-site.xml
      volumes:
      - name: nifi-data-in
        hostPath: 
          path: /var/k8s/nifi/nifi-data-in
          type: DirectoryOrCreate
      - name: nifi-data-out
        hostPath: 
          path: /var/k8s/nifi/nifi-data-out
          type: DirectoryOrCreate
      - name: nifi-conf
        hostPath: 
          path: /var/k8s/nifi/conf
          type: DirectoryOrCreate
      - name: nifi-config-hadoop-core-site
        secret:
          secretName: nifi-config-hadoop-core-site
      - name: nifi-config-hadoop-hdfs-site
        secret:
          secretName: nifi-config-hadoop-hdfs-site
      nodeSelector:
        server-type: nifi
  volumeClaimTemplates:
---
